# Generated by Django 5.0.4 on 2024-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cgpa_track',
            fields=[
                ('Reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester1', models.CharField(blank=True, max_length=100, null=True)),
                ('semester2', models.CharField(blank=True, max_length=100, null=True)),
                ('semester3', models.CharField(blank=True, max_length=100, null=True)),
                ('semester4', models.CharField(blank=True, max_length=100, null=True)),
                ('semester5', models.CharField(blank=True, max_length=100, null=True)),
                ('semester6', models.CharField(blank=True, max_length=100, null=True)),
                ('semester7', models.CharField(blank=True, max_length=100, null=True)),
                ('semester8', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('course_count', models.CharField(max_length=100)),
                ('coursecode1', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits1', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode2', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits2', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode3', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits3', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode4', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits4', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode5', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits5', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode6', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits6', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode7', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits7', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode8', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits8', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode9', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits9', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode10', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits10', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode11', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits11', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecode12', models.CharField(blank=True, max_length=100, null=True)),
                ('coursecredits12', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_no', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=100)),
                ('course_count', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('coursegrade1', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade2', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade3', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade4', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade5', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade6', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade7', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade8', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade9', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade10', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade11', models.CharField(blank=True, max_length=100, null=True)),
                ('coursegrade12', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
