# Generated by Django 5.0.4 on 2024-06-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgpa_track',
            name='cgpa',
            field=models.CharField(default=7.8, max_length=100),
            preserve_default=False,
        ),
    ]
